use crate::migration::types::{MigrationResult, MigrationStatus};
use crate::terraform::types::TerraformResource;

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn make_res(resource_type: &str, name: &str, attrs: &[(&str, &str)]) -> TerraformResource {
        TerraformResource {
            resource_type: resource_type.to_string(),
            name: name.to_string(),
            attributes: attrs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect(),
            source_file: PathBuf::from("test.tf"),
            raw_hcl: String::new(),
        }
    }

    // ── map_lb ────────────────────────────────────────────────────────────────

    #[test]
    fn public_lb_generates_public_networks_block() {
        let res = make_res("aws_lb", "main", &[("internal", "false")]);
        let r = map_lb(&res);
        assert_eq!(r.upcloud_type, "upcloud_loadbalancer");
        let hcl = r.upcloud_hcl.unwrap();
        assert!(hcl.contains("resource \"upcloud_loadbalancer\" \"main\""), "{hcl}");
        assert!(hcl.contains("type   = \"public\""), "{hcl}");
        // public LB also requires a private network for backend connectivity
        assert!(hcl.contains("type    = \"private\""), "public LB must also have private network block\n{hcl}");
        // `network = ...` is only valid inside a networks {} block (4-space indent), not as a deprecated
        // top-level attribute (2-space indent) on the upcloud_loadbalancer resource
        assert!(!hcl.contains("\n  network = "), "must not use deprecated top-level network attr\n{hcl}");
    }

    #[test]
    fn internal_lb_generates_private_networks_block_with_todo() {
        let res = make_res("aws_lb", "internal", &[("internal", "true")]);
        let hcl = map_lb(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("type    = \"private\""), "{hcl}");
        assert!(
            hcl.contains("<TODO: upcloud_network reference>"),
            "internal LB should have network TODO\n{hcl}"
        );
    }

    #[test]
    fn lb_without_internal_attr_defaults_to_public() {
        let res = make_res("aws_lb", "def", &[]);
        let hcl = map_lb(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("type   = \"public\""), "{hcl}");
    }

    #[test]
    fn lb_has_configured_status_started() {
        let res = make_res("aws_lb", "lb", &[]);
        let hcl = map_lb(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("configured_status = \"started\""), "{hcl}");
    }

    // ── map_lb_target_group ───────────────────────────────────────────────────

    #[test]
    fn lb_target_group_generates_backend_only() {
        let res = make_res("aws_lb_target_group", "web", &[
            ("protocol", "HTTP"),
            ("port", "80"),
        ]);
        let r = map_lb_target_group(&res);
        assert_eq!(r.upcloud_type, "upcloud_loadbalancer_backend");
        let hcl = r.upcloud_hcl.unwrap();
        assert!(hcl.contains("resource \"upcloud_loadbalancer_backend\" \"web\""), "{hcl}");
        // No stub member — members are generated by aws_lb_target_group_attachment resources.
        assert!(
            !hcl.contains("upcloud_loadbalancer_static_backend_member"),
            "target_group must NOT emit a stub member — attachments generate the real members\n{hcl}"
        );
    }

    #[test]
    fn lb_target_group_has_lb_cross_ref_todo() {
        let res = make_res("aws_lb_target_group", "tg", &[]);
        let hcl = map_lb_target_group(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("upcloud_loadbalancer.<TODO>.id"), "{hcl}");
    }

    #[test]
    fn lb_target_group_maps_health_check_properties() {
        let res = make_res("aws_lb_target_group", "web", &[
            ("protocol", "HTTP"),
            ("port", "80"),
            ("health_check.path", "\"/health\""),
            ("health_check.matcher", "\"200\""),
            ("health_check.healthy_threshold", "\"3\""),
            ("health_check.unhealthy_threshold", "\"2\""),
            ("health_check.interval", "\"30\""),
        ]);
        let hcl = map_lb_target_group(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("health_check_type   = \"http\""), "{hcl}");
        assert!(hcl.contains("health_check_url    = \"/health\""), "{hcl}");
        assert!(hcl.contains("health_check_expected_status = 200"), "{hcl}");
        assert!(hcl.contains("health_check_rise   = 3"), "{hcl}");
        assert!(hcl.contains("health_check_fall   = 2"), "{hcl}");
        assert!(hcl.contains("health_check_interval = 30"), "{hcl}");
    }

    #[test]
    fn lb_target_group_without_health_check_still_has_type() {
        // health_check_type defaults based on protocol even without explicit health_check block
        let res = make_res("aws_lb_target_group", "api", &[("protocol", "HTTP")]);
        let hcl = map_lb_target_group(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("health_check_type   = \"http\""), "{hcl}");
        assert!(!hcl.contains("health_check_url"), "no url when path not set\n{hcl}");
    }

    #[test]
    fn lb_target_group_tcp_protocol_uses_tcp_health_check() {
        let res = make_res("aws_lb_target_group", "nl", &[("protocol", "TCP")]);
        let hcl = map_lb_target_group(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("health_check_type   = \"tcp\""), "{hcl}");
    }

    // ── map_lb_listener ───────────────────────────────────────────────────────

    #[test]
    fn lb_listener_generates_frontend() {
        let res = make_res("aws_lb_listener", "http", &[
            ("protocol", "HTTP"),
            ("port", "80"),
        ]);
        let r = map_lb_listener(&res);
        assert_eq!(r.upcloud_type, "upcloud_loadbalancer_frontend");
        let hcl = r.upcloud_hcl.unwrap();
        assert!(hcl.contains("resource \"upcloud_loadbalancer_frontend\" \"http\""), "{hcl}");
        assert!(hcl.contains("port                 = 80"), "{hcl}");
    }

    #[test]
    fn lb_listener_has_lb_and_backend_cross_ref_todos() {
        let res = make_res("aws_lb_listener", "lst", &[]);
        let hcl = map_lb_listener(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("upcloud_loadbalancer.<TODO>.id"), "{hcl}");
        assert!(hcl.contains("upcloud_loadbalancer_backend.<TODO>.name"), "{hcl}");
    }

    #[test]
    fn lb_listener_http_uses_http_mode() {
        let res = make_res("aws_lb_listener", "http", &[("protocol", "HTTP"), ("port", "80")]);
        let hcl = map_lb_listener(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("mode                 = \"http\""), "{hcl}");
    }

    #[test]
    fn lb_listener_tcp_uses_tcp_mode() {
        let res = make_res("aws_lb_listener", "tcp", &[("protocol", "TCP"), ("port", "443")]);
        let hcl = map_lb_listener(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("mode                 = \"tcp\""), "{hcl}");
    }

    #[test]
    fn lb_listener_has_networks_block() {
        let res = make_res("aws_lb_listener", "http", &[("protocol", "HTTP"), ("port", "80")]);
        let hcl = map_lb_listener(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("networks {"), "{hcl}");
        assert!(hcl.contains("name = \"public\""), "{hcl}");
    }

    #[test]
    fn lb_listener_redirect_action_generates_frontend_rule() {
        let res = make_res("aws_lb_listener", "http", &[
            ("protocol", "HTTP"),
            ("port", "80"),
            ("default_action.type", "redirect"),
            ("default_action.redirect.port", "443"),
            ("default_action.redirect.protocol", "HTTPS"),
        ]);
        let hcl = map_lb_listener(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("upcloud_loadbalancer_frontend_rule"), "redirect must generate a frontend rule\n{hcl}");
        assert!(hcl.contains("http_redirect"), "{hcl}");
        assert!(hcl.contains("https://"), "redirect target must use https\n{hcl}");
        assert!(hcl.contains(":443"), "redirect target must include port 443\n{hcl}");
    }

    #[test]
    fn lb_listener_forward_action_has_no_redirect_rule() {
        let res = make_res("aws_lb_listener", "https", &[
            ("protocol", "HTTPS"),
            ("port", "443"),
        ]);
        let hcl = map_lb_listener(&res).upcloud_hcl.unwrap();
        assert!(!hcl.contains("http_redirect"), "forward listener must not generate redirect rule\n{hcl}");
    }

    #[test]
    fn lb_listener_https_generates_tls_config() {
        let res = make_res("aws_lb_listener", "https", &[
            ("protocol", "HTTPS"),
            ("port", "443"),
        ]);
        let hcl = map_lb_listener(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("upcloud_loadbalancer_frontend_tls_config"), "HTTPS listener must generate TLS config\n{hcl}");
        assert!(hcl.contains("certificate_bundle "), "{hcl}");
        assert!(hcl.contains("upcloud_loadbalancer_manual_certificate_bundle.<TODO>.id"), "{hcl}");
    }

    #[test]
    fn lb_listener_http_has_no_tls_config() {
        let res = make_res("aws_lb_listener", "http", &[("protocol", "HTTP"), ("port", "80")]);
        let hcl = map_lb_listener(&res).upcloud_hcl.unwrap();
        assert!(!hcl.contains("tls_config"), "HTTP listener must not generate TLS config\n{hcl}");
    }

    // ── map_lb_target_group_attachment ────────────────────────────────────────

    #[test]
    fn lb_target_group_attachment_generates_static_backend_member() {
        let res = make_res("aws_lb_target_group_attachment", "tga", &[
            ("target_group_arn", "aws_lb_target_group.web.arn"),
            ("target_id", "aws_instance.app.id"),
            ("port", "8080"),
        ]);
        let r = map_lb_target_group_attachment(&res);
        assert_eq!(r.upcloud_type, "upcloud_loadbalancer_static_backend_member");
        let hcl = r.upcloud_hcl.unwrap();
        assert!(hcl.contains("resource \"upcloud_loadbalancer_static_backend_member\" \"tga\""), "{hcl}");
        assert!(hcl.contains("upcloud_loadbalancer_backend.web.id"), "{hcl}");
        assert!(hcl.contains("port         = 8080"), "{hcl}");
        assert!(hcl.contains("max_sessions = 1000"), "{hcl}");
        assert!(hcl.contains("weight       = 100"), "{hcl}");
        // No count: should use a TODO for the IP
        assert!(hcl.contains("upcloud_server.app IP"), "{hcl}");
    }

    #[test]
    fn lb_target_group_attachment_with_count_uses_count_index_ip() {
        let res = make_res("aws_lb_target_group_attachment", "web", &[
            ("target_group_arn", "aws_lb_target_group.web.arn"),
            ("target_id", "aws_instance.web[count.index].id"),
            ("port", "80"),
            ("count", "var.web_server_count"),
        ]);
        let hcl = map_lb_target_group_attachment(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("count        = var.web_server_count"), "count should be propagated\n{hcl}");
        assert!(hcl.contains("upcloud_server.web[count.index].network_interface[1].ip_address"), "should use private interface with count.index\n{hcl}");
        assert!(hcl.contains("web-${count.index + 1}"), "name should be unique per index\n{hcl}");
    }

    #[test]
    fn lb_target_group_attachment_with_literal_index_resolves_ip() {
        let res = make_res("aws_lb_target_group_attachment", "web_1", &[
            ("target_group_arn", "aws_lb_target_group.web.arn"),
            ("target_id", "aws_instance.web[0].id"),
            ("port", "8080"),
        ]);
        let hcl = map_lb_target_group_attachment(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("upcloud_server.web[0].network_interface[1].ip_address"),
            "literal index should auto-resolve to indexed server private interface\n{hcl}");
        assert!(!hcl.contains("<TODO"), "no TODOs should remain when index is known\n{hcl}");
    }

    #[test]
    fn lb_target_group_attachment_without_refs_has_todos() {
        let res = make_res("aws_lb_target_group_attachment", "tga", &[]);
        let hcl = map_lb_target_group_attachment(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("<TODO: backend>"), "{hcl}");
        assert!(hcl.contains("<TODO: server IP address>"), "{hcl}");
    }

    // ── map_acm_certificate ───────────────────────────────────────────────────

    #[test]
    fn acm_cert_generates_manual_cert_bundle() {
        let res = make_res("aws_acm_certificate", "cert", &[]);
        let r = map_acm_certificate(&res);
        assert_eq!(r.upcloud_type, "upcloud_loadbalancer_manual_certificate_bundle");
        let hcl = r.upcloud_hcl.unwrap();
        assert!(hcl.contains("resource \"upcloud_loadbalancer_manual_certificate_bundle\" \"cert\""), "{hcl}");
    }

    #[test]
    fn acm_cert_has_certificate_and_private_key_todos() {
        let res = make_res("aws_acm_certificate", "cert", &[]);
        let hcl = map_acm_certificate(&res).upcloud_hcl.unwrap();
        assert!(hcl.contains("<TODO: base64 encoded certificate>"), "{hcl}");
        assert!(hcl.contains("<TODO: base64 encoded private key>"), "{hcl}");
    }

    #[test]
    fn acm_cert_is_partial_status() {
        let res = make_res("aws_acm_certificate", "cert", &[]);
        assert_eq!(
            map_acm_certificate(&res).status,
            crate::migration::types::MigrationStatus::Partial
        );
    }
}

pub fn map_lb(res: &TerraformResource) -> MigrationResult {
    let lb_type = res.attributes.get("load_balancer_type").map(|t| t.trim_matches('"')).unwrap_or("application");
    let is_internal = res.attributes.get("internal").map(|v| v.trim_matches('"') == "true").unwrap_or(false);

    // UpCloud LBs require at least one private network block for backend connectivity.
    // Public LBs additionally include a public network block for internet-facing traffic.
    let networks_block = if is_internal {
        r#"  networks {
    name    = "private"
    type    = "private"
    family  = "IPv4"
    network = "<TODO: upcloud_network reference>"
  }"#.to_string()
    } else {
        r#"  networks {
    name    = "private"
    type    = "private"
    family  = "IPv4"
    network = "<TODO: upcloud_network reference>"
  }

  networks {
    name   = "public"
    type   = "public"
    family = "IPv4"
  }"#.to_string()
    };

    let hcl = format!(
        r#"resource "upcloud_loadbalancer" "{name}" {{
  name              = "{name}"
  plan              = "development"  # update to production-small or higher for production
  zone              = "__ZONE__"
  configured_status = "started"

{networks}

  # Backends and frontends are separate resources
}}
"#,
        name = res.name,
        networks = networks_block,
    );

    let mut notes = vec![
        format!("ALB/NLB ({}) → UpCloud Load Balancer", lb_type),
        "Backends and frontends are defined as separate Terraform resources".into(),
    ];
    if is_internal {
        notes.push("Internal LB: private network reference will be auto-resolved if a subnet exists.".into());
    }

    MigrationResult {
        resource_type: res.resource_type.clone(),
        resource_name: res.name.clone(),
        source_file: res.source_file.display().to_string(),
        status: MigrationStatus::Compatible,
        score: 78,
        upcloud_type: "upcloud_loadbalancer".into(),
        upcloud_hcl: Some(hcl),
        snippet: None,
        parent_resource: None,
        notes,
        source_hcl: None,
    }
}

pub fn map_lb_target_group(res: &TerraformResource) -> MigrationResult {
    let protocol = res.attributes.get("protocol").map(|p| p.trim_matches('"')).unwrap_or("HTTP");
    let port = res.attributes.get("port").map(|p| p.trim_matches('"')).unwrap_or("80");

    // Map health_check block attributes to UpCloud backend properties.
    // hcl-rs stores nested block attrs with dot-prefix: "health_check.path", etc.
    let hc_type = match protocol.to_uppercase().as_str() {
        "HTTP" | "HTTPS" => "http",
        _ => "tcp",
    };
    let hc_url = res.attributes.get("health_check.path")
        .map(|v| v.trim_matches('"').to_string());
    let hc_status = res.attributes.get("health_check.matcher")
        .and_then(|v| v.trim_matches('"').parse::<u32>().ok());
    let hc_rise = res.attributes.get("health_check.healthy_threshold")
        .and_then(|v| v.trim_matches('"').parse::<u32>().ok());
    let hc_fall = res.attributes.get("health_check.unhealthy_threshold")
        .and_then(|v| v.trim_matches('"').parse::<u32>().ok());
    let hc_interval = res.attributes.get("health_check.interval")
        .and_then(|v| v.trim_matches('"').parse::<u32>().ok());

    let mut hc_lines = format!("    health_check_type   = \"{hc_type}\"\n");
    if let Some(url) = &hc_url {
        hc_lines.push_str(&format!("    health_check_url    = \"{url}\"\n"));
    }
    if let Some(status) = hc_status {
        hc_lines.push_str(&format!("    health_check_expected_status = {status}\n"));
    }
    if let Some(rise) = hc_rise {
        hc_lines.push_str(&format!("    health_check_rise   = {rise}\n"));
    }
    if let Some(fall) = hc_fall {
        hc_lines.push_str(&format!("    health_check_fall   = {fall}\n"));
    }
    if let Some(interval) = hc_interval {
        hc_lines.push_str(&format!("    health_check_interval = {interval}\n"));
    }

    let hcl = format!(
        r#"resource "upcloud_loadbalancer_backend" "{name}" {{
  loadbalancer = upcloud_loadbalancer.<TODO>.id
  name         = "{name}"

  properties {{
{hc_lines}  }}
}}
"#,
        name = res.name,
        hc_lines = hc_lines,
    );

    let mut notes = vec![
        format!("Target group ({}/{}) → upcloud_loadbalancer_backend.", protocol, port),
        "Backend members are generated from aws_lb_target_group_attachment resources. If none exist, add an upcloud_loadbalancer_static_backend_member manually.".into(),
    ];
    if hc_url.is_some() || hc_status.is_some() {
        notes.push("Health check settings mapped from aws_lb_target_group health_check block.".into());
    }

    MigrationResult {
        resource_type: res.resource_type.clone(),
        resource_name: res.name.clone(),
        source_file: res.source_file.display().to_string(),
        status: MigrationStatus::Compatible,
        score: 74,
        upcloud_type: "upcloud_loadbalancer_backend".into(),
        upcloud_hcl: Some(hcl),
        snippet: None,
        parent_resource: None,
        notes,
        source_hcl: None,
    }
}

pub fn map_lb_listener(res: &TerraformResource) -> MigrationResult {
    let protocol = res.attributes.get("protocol").map(|p| p.trim_matches('"')).unwrap_or("HTTP");
    let port = res.attributes.get("port").map(|p| p.trim_matches('"')).unwrap_or("80");
    // tcp mode for layer-4 (TCP/TLS/UDP), http mode for layer-7 (HTTP/HTTPS)
    let upcloud_mode = match protocol.to_uppercase().as_str() {
        "TCP" | "TLS" | "UDP" => "tcp",
        _ => "http",
    };
    // frontend networks block: specifies which LB network this listener is on.
    let network_name = "public";

    let action_type = res.attributes.get("default_action.type")
        .map(|v| v.trim_matches('"'))
        .unwrap_or("forward");
    let is_redirect = action_type == "redirect";

    // For redirect listeners the frontend still needs a backend (even if the redirect
    // rule handles all traffic). Use a TODO so the generator can auto-resolve it.
    let mut hcl = format!(
        r#"resource "upcloud_loadbalancer_frontend" "{name}" {{
  loadbalancer         = upcloud_loadbalancer.<TODO>.id
  name                 = "{name}"
  mode                 = "{mode}"
  port                 = {port}
  default_backend_name = upcloud_loadbalancer_backend.<TODO>.name

  networks {{
    name = "{network_name}"  # must match network name in upcloud_loadbalancer
  }}
}}
"#,
        name = res.name,
        mode = upcloud_mode,
        port = port,
        network_name = network_name,
    );

    // For redirect listeners (e.g. HTTP → HTTPS), generate a frontend rule that
    // performs the redirect. UpCloud uses upcloud_loadbalancer_frontend_rule with
    // an http_redirect action (HAProxy location string).
    if is_redirect {
        let redirect_port = res.attributes.get("default_action.redirect.port")
            .map(|v| v.trim_matches('"'))
            .unwrap_or("443");
        let redirect_proto = res.attributes.get("default_action.redirect.protocol")
            .map(|v| v.trim_matches('"').to_lowercase())
            .unwrap_or_else(|| "https".into());
        hcl.push_str(&format!(
            r#"
resource "upcloud_loadbalancer_frontend_rule" "{name}_redirect" {{
  frontend = upcloud_loadbalancer_frontend.{name}.id
  name     = "{name}-redirect"
  priority = 100

  actions {{
    http_redirect {{
      location = "{proto}://{{{{req.hdr(host)}}}}:{port}{{{{req.path}}}}"
    }}
  }}
}}
"#,
            name = res.name,
            proto = redirect_proto,
            port = redirect_port,
        ));
    }

    // For HTTPS listeners, generate a TLS config resource that binds the certificate.
    if protocol.to_uppercase() == "HTTPS" {
        hcl.push_str(&format!(
            r#"
resource "upcloud_loadbalancer_frontend_tls_config" "{name}_tls" {{
  frontend                = upcloud_loadbalancer_frontend.{name}.id
  name                    = "{name}-tls"
  certificate_bundle = upcloud_loadbalancer_manual_certificate_bundle.<TODO>.id
}}
"#,
            name = res.name,
        ));
    }

    let mut notes = vec![format!("Listener ({}/{}) → UpCloud LB Frontend (mode={})", protocol, port, upcloud_mode)];
    if is_redirect {
        notes.push(format!(
            "HTTP redirect action → upcloud_loadbalancer_frontend_rule '{}_redirect' generated.",
            res.name
        ));
    }
    if protocol.to_uppercase() == "HTTPS" {
        notes.push(format!(
            "HTTPS: upcloud_loadbalancer_frontend_tls_config '{}_tls' generated — cert bundle auto-resolved.",
            res.name
        ));
    }

    MigrationResult {
        resource_type: res.resource_type.clone(),
        resource_name: res.name.clone(),
        source_file: res.source_file.display().to_string(),
        status: MigrationStatus::Compatible,
        score: 74,
        upcloud_type: "upcloud_loadbalancer_frontend".into(),
        upcloud_hcl: Some(hcl),
        snippet: None,
        parent_resource: None,
        notes,
        source_hcl: None,
    }
}

pub fn map_lb_target_group_attachment(res: &TerraformResource) -> MigrationResult {
    // aws_lb_target_group_attachment → upcloud_loadbalancer_static_backend_member
    let backend_name = res.attributes.get("target_group_arn").and_then(|v| {
        let v = v.trim_matches('"');
        if v.starts_with("aws_lb_target_group.") || v.starts_with("aws_alb_target_group.") {
            v.split('.').nth(1).map(str::to_string)
        } else {
            None
        }
    });
    let target_id = res.attributes.get("target_id").map(|v| v.trim_matches('"').to_string());
    let port = res.attributes.get("port").map(|v| v.trim_matches('"').to_string()).unwrap_or_else(|| "80".to_string());

    // Propagate count if the attachment has it (e.g. count = var.web_server_count)
    let count_attr = res.attributes.get("count").map(|v| v.trim_matches('"').to_string());
    let has_count = count_attr.is_some();

    let backend_ref = backend_name.as_deref().unwrap_or("<TODO: backend>");

    // Extract the base server name and optional literal numeric index.
    // e.g. "aws_instance.web[0].id"           → name="web", literal_idx=Some("0")
    // e.g. "aws_instance.web[count.index].id" → name="web", literal_idx=None (has_count handles it)
    // e.g. "aws_instance.app.id"              → name="app", literal_idx=None
    let (server_name, server_literal_index): (Option<String>, Option<String>) =
        target_id.as_deref()
        .map(|id| {
            if id.starts_with("aws_instance.") {
                let rest = &id["aws_instance.".len()..];
                let base = rest.split(|c: char| c == '.' || c == '[').next().unwrap_or(rest);
                if base.is_empty() { return (None, None); }
                let literal_idx = rest.find('[').and_then(|bi| {
                    let inner = &rest[bi + 1..];
                    inner.find(']').and_then(|ei| {
                        let s = &inner[..ei];
                        if s.chars().all(|c| c.is_ascii_digit()) { Some(s.to_string()) } else { None }
                    })
                });
                (Some(base.to_string()), literal_idx)
            } else {
                (None, None)
            }
        })
        .unwrap_or((None, None));

    // Build count + name lines.
    let count_name_lines = if let Some(ref n) = count_attr {
        format!("  count        = {}\n  name         = \"{}-${{count.index + 1}}\"\n", n, res.name)
    } else {
        format!("  name         = \"{}\"\n", res.name)
    };

    // Build the IP line using network_interface[1] (private) for LB backend traffic.
    // Priority: count.index > literal index > TODO.
    let ip_line = match (&server_name, has_count, &server_literal_index) {
        (Some(inst), true, _) => {
            format!("  ip           = upcloud_server.{}[count.index].network_interface[1].ip_address\n", inst)
        }
        (Some(inst), false, Some(idx)) => {
            format!("  ip           = upcloud_server.{}[{}].network_interface[1].ip_address\n", inst, idx)
        }
        (Some(inst), false, None) => {
            format!("  ip           = \"<TODO: upcloud_server.{} IP>\"\n", inst)
        }
        _ => "  ip           = \"<TODO: server IP address>\"\n".to_string(),
    };

    let hcl = format!(
        "resource \"upcloud_loadbalancer_static_backend_member\" \"{name}\" {{\n\
         {count_name_lines}\
         backend      = upcloud_loadbalancer_backend.{backend}.id\n\
         {ip_line}\
           port         = {port}\n\
           weight       = 100\n\
           max_sessions = 1000\n\
           enabled      = true\n\
         }}\n",
        name = res.name,
        count_name_lines = count_name_lines,
        backend = backend_ref,
        ip_line = ip_line,
        port = port,
    );

    let mut notes = vec![
        "Target group attachment → static_backend_member.".into(),
    ];
    if has_count {
        notes.push("count propagated; IP references server's private interface (network_interface[1]).".into());
    } else if server_literal_index.is_some() {
        notes.push("IP auto-resolved from target_id index → network_interface[1] (private).".into());
    } else {
        notes.push("Update ip to the server's actual IP or floating IP.".into());
    }

    MigrationResult {
        resource_type: res.resource_type.clone(),
        resource_name: res.name.clone(),
        source_file: res.source_file.display().to_string(),
        status: MigrationStatus::Compatible,
        score: 70,
        upcloud_type: "upcloud_loadbalancer_static_backend_member".into(),
        upcloud_hcl: Some(hcl),
        snippet: None,
        parent_resource: backend_name,
        notes,
        source_hcl: None,
    }
}

pub fn map_acm_certificate(res: &TerraformResource) -> MigrationResult {
    let hcl = format!(
        r#"resource "upcloud_loadbalancer_manual_certificate_bundle" "{name}" {{
  name        = "{name}"
  certificate = "<TODO: base64 encoded certificate>"
  private_key = "<TODO: base64 encoded private key>"
}}
"#,
        name = res.name,
    );

    MigrationResult {
        resource_type: res.resource_type.clone(),
        resource_name: res.name.clone(),
        source_file: res.source_file.display().to_string(),
        status: MigrationStatus::Partial,
        score: 40,
        upcloud_type: "upcloud_loadbalancer_manual_certificate_bundle".into(),
        upcloud_hcl: Some(hcl),
        snippet: None,
        parent_resource: None,
        notes: vec![
            "ACM → UpCloud manual cert bundle. Export cert/key from ACM first.".into(),
            "No automatic certificate provisioning equivalent.".into(),
        ],
        source_hcl: None,
    }
}
